- name: Create a EC2 Web application
  hosts: localhost
  gather_facts: False
  vars:
    aws_access_key: 'AKIAQGSGIAX5HNVTTZPS'
    aws_secret_key: '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'
    vpc_title: 'Flask-Times-News-VPC'
    vpc_name: '{{ vpc_title }} VPC'
    security_group_name: '{{ vpc_title }} Security'
    route_table_name: '{{ vpc_title }} route table'
    acl_name: '{{ vpc_title}} ACL'
    subnet_name: '{{ vpc_title }} Subnet'
    igw_name: '{{ vpc_title }} IGW'
    vpcCidrBlock: '10.0.0.0/16'
    subNetCidrBlock: '10.0.1.0/24'
    port22CidrBlock: '0.0.0.0/0'
    port80CidrBlock: '0.0.0.0/0'
    destinationCidrBlock: '0.0.0.0/0'
    state: 'present'
    zone: 'us-west-2a'
    private_key:
    playbook_dir: "news"
    instance_type: t2.micro
    image: ami-0d70546e43a941d70
    region: us-west-2
  roles:
    - aws
  
- name: Deploying Flask News Api Application
  hosts: launched
  remote_user: ubuntu
  become: True
  gather_facts: False
  roles:
    - flask