---
- name: apt-get update
  raw: "apt-get -y update -qq"
- name: install python
  raw: "apt-get -y install python3.9 python3-pip"
- action: setup
- name: install flask
  pip:
    name: flask
- name: install news-api for python
  pip:
    name: newsapi-python
- name: copy flask app file
  copy:
    src: application.py
    dest: /home/ubuntu/application.py
    owner: ubuntu
    group: ubuntu
    mode: 0755
- name: copy html file
  copy:
    src: templates/home.html
    dest: /home/ubuntu/home.html
    owner: ubuntu
    group: ubuntu
    mode: 0755
- name: copy css file
  copy:
    src: static/style.css
    dest: /home/ubuntu/style.css
    owner: ubuntu
    group: ubuntu
    mode: 0755
- name: copy flask systemd file
  copy: 
    src: flask.service
    dest: /etc/systemd/system/flask.service
    owner: root
    group: root
    mode: 0755
- name: enable flask service
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: flask.service
